<a href="https://colab.research.google.com/github/swapnilxi/computer-vision/blob/main/ComputerVision_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
# prompt: install and import numpy

pip install numpy
import numpy as np


## List and Numpy Arrays

### type of array and converting to numpy

In [ ]:
myList = [1,2,3]
type(myList)

list

In [ ]:
myArray= np.array(myList)


In [ ]:
type(myArray)

numpy.ndarray

### Arranging the numpy Array

syntax: np.arange([start,] stop[, step,], dtype=None)

dtype: The type of the output array. If not provided, it is inferred from the other arguments.

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

**zeros**

numpy.zeros(shape, dtype=float, order='C') -  rows and columns

In [ ]:
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

**ones**

In [ ]:
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

dtype

In [ ]:
array = np.arange(0, 2.1, 0.5, dtype=float)
print(array)

[0.  0.5 1.  1.5 2. ]


#### creating same random number every time - using seed
syntax: numpy.random.randint(low, high=None, size=None, dtype=int)

In [ ]:
np.random.seed(102)
random_integers = np.random.randint(0,  100, 10)
print("Random integers:", random_integers)

Random integers: [ 0 78 66 73 72 45 72 73 79  7]


In [ ]:
arr = random_integers
arr

array([ 0, 78, 66, 73, 72, 45, 72, 73, 79,  7])

*

In [ ]:
arr.max()

79

**argMax** - Find the index of the maximum value

In [ ]:
arr.argmax()

8

In [ ]:
arr.argmin()

0

In [ ]:
arr.mean()

56.5

In [ ]:
arr.shape

(10,)

single-element tuple (10,). tuple - Immutable objects


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr1= arr

In [ ]:
arr_reshape= arr1.reshape(2,5)
arr_reshape

array([[ 0, 78, 66, 73, 72],
       [45, 72, 73, 79,  7]])

matrix_resize

In [ ]:
mat= np.arange(0,25).reshape(5,5)
mat


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# New Section