<a href="https://colab.research.google.com/github/swapnilxi/A-computer-vision/blob/main/keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy import genfromtxt

In [ ]:
data = genfromtxt('/content/drive/MyDrive/Colab Notebooks/ComputerVision/ImageData/bank_note_data.txt', delimiter=',')
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

0 and 1 are label to show not are real of fake , in next step we are going to seprate real feature from the feature list

In [ ]:
labels= data[:,4]
labels

array([0., 0., 0., ..., 1., 1., 1.])

now grabbing the feature getting everything except 4th column

In [ ]:
features= data[:,0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

##Test and Train data
let's make a test and training set data before doing That 's call label as X and features as y

In [ ]:
X= features
y= labels

In [ ]:
from sklearn.model_selection import train_test_split

testSize meaning it will take 30% data from X and 30% from y, also random_state is convention from book which will shuffle the data and auto sort it

In [ ]:
X_train, X_test, y_train, y_test =train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

60-30% distribution between train and test data set

In [ ]:
len(X), len(X_train), len(X_test)

(1372, 919, 453)

In [ ]:
X_test.min(), X_test.max()

(-13.2869, 17.1116)

the range of min and max is similar, if one is like million and other like in 100 then it is good idea to have min max scaler

In [ ]:
import sklearn
from sklearn.preprocessing import MinMaxScaler

# Initialize MinMaxScaler
scaler_object = MinMaxScaler()

In [ ]:
scaler_object.fit(X_train)

MinMaxScaler()

In [ ]:
scaled_X_train= scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

we are only fitting the the training the training data not test else that mean we are purpousefully trying to peek and manipulate into test data

#Keras
- adding the dense layer


In [ ]:
!pip install tensorflow
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

## creating a model
model = Sequential()  
- This line creates a Sequential model.
- A Sequential model is a linear stack of layers in Keras, meaning the layers are added one after another in a sequence. It's the simplest way to build a neural network in Keras.



**model.add()**  
This is how you add layers to your Sequential model.

Dense(4, ...): This adds a Dense layer, which is a type of layer where each node is connected to every node in the previous layer.  

The first argument ***4*** specifies the number of neurons (nodes) in this layer.
Neurons process information received from the previous layer.

**input_dim=4**  
 This is specific to the input layer. It tells the layer that it should expect input data with 4 features. This matches the number of features in our dataset (after preprocessing).

 like we have 4 input features in bank notes

input_dim=4: This is specific to the input layer. It tells the layer that it should expect input data with 4 features. This matches the number of features in our dataset (after preprocessing).

In [ ]:
model = Sequential()
#input
model.add(Dense(4, input_dim=4, activation='relu'))
#mid layer or hidden layer
model.add(Dense(8, activation='relu'))
#output -sigmoid is 0 or 1
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


model.compile(): This is a function in Keras that configures the model for training. Think of it as setting the rules and objectives for the learning process.

loss='binary_crossentropy': This defines the loss function, which measures how well the model's predictions match the actual data during training.

binary_crossentropy is a common loss function used for binary classification problems, where the goal is to predict one of two classes (in this case, real or fake banknotes).
The model aims to minimize this loss function during training.

optimizer='adam': This specifies the optimization algorithm used to update the model's weights during training.


adam (Adaptive Moment Estimation) is a popular optimization algorithm known for its efficiency and good performance.
It automatically adjusts the learning rate during training, making the process smoother and potentially faster.
metrics=['accuracy']: This defines the metrics used to evaluate the model's performance.


accuracy is a common metric that measures the percentage of correctly classified samples.
The model's accuracy will be tracked during training and reported after each epoch (a full pass through the training data).

In [ ]:
model.compile( loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(scaled_X_train, y_train, epochs=50, verbose=2)

Epoch 1/50
29/29 - 2s - 78ms/step - accuracy: 0.5517 - loss: 0.6571
Epoch 2/50
29/29 - 0s - 14ms/step - accuracy: 0.5887 - loss: 0.6514
Epoch 3/50
29/29 - 0s - 5ms/step - accuracy: 0.6137 - loss: 0.6461
Epoch 4/50
29/29 - 0s - 5ms/step - accuracy: 0.6235 - loss: 0.6407
Epoch 5/50
29/29 - 0s - 5ms/step - accuracy: 0.6289 - loss: 0.6346
Epoch 6/50
29/29 - 0s - 3ms/step - accuracy: 0.6387 - loss: 0.6273
Epoch 7/50
29/29 - 0s - 4ms/step - accuracy: 0.6561 - loss: 0.6200
Epoch 8/50
29/29 - 0s - 5ms/step - accuracy: 0.6627 - loss: 0.6131
Epoch 9/50
29/29 - 0s - 5ms/step - accuracy: 0.6790 - loss: 0.6055
Epoch 10/50
29/29 - 0s - 3ms/step - accuracy: 0.6823 - loss: 0.5976
Epoch 11/50
29/29 - 0s - 5ms/step - accuracy: 0.6834 - loss: 0.5892
Epoch 12/50
29/29 - 0s - 4ms/step - accuracy: 0.6855 - loss: 0.5806
Epoch 13/50
29/29 - 0s - 3ms/step - accuracy: 0.6877 - loss: 0.5716
Epoch 14/50
29/29 - 0s - 5ms/step - accuracy: 0.6997 - loss: 0.5622
Epoch 15/50
29/29 - 0s - 5ms/step - accuracy: 0.7095 - 

In [ ]:
model.metrics_names

['loss', 'compile_metrics']

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
predictions = (model.predict(scaled_X_test) > 0.5).astype("int32")
# Use model.predict and convert probabilities to class labels (0 or 1).
# Values above 0.5 will be assigned to class 1 and below will to 0.

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step


In [ ]:
confusion_matrix_result= confusion_matrix(y_test, predictions)
print(confusion_matrix)

[[256   1]
 [ 10 186]]


In [ ]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.96      1.00      0.98       257
         1.0       0.99      0.95      0.97       196

    accuracy                           0.98       453
   macro avg       0.98      0.97      0.98       453
weighted avg       0.98      0.98      0.98       453



## saving and using the model

In [ ]:
model.save("superModel.h5")

In [ ]:
from keras.models import load_model
newModel= load_model("superModel.h5")

In [ ]:
newModel.predict(scaled_X_test)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 


array([[5.04086018e-02],
       [4.29818720e-01],
       [2.74152845e-01],
       [4.06032912e-02],
       [4.39084619e-02],
       [2.58217417e-02],
       [1.29728004e-01],
       [1.19485296e-02],
       [3.77455838e-02],
       [8.14055577e-02],
       [5.73917389e-01],
       [8.71387362e-01],
       [1.04014464e-01],
       [8.06159019e-01],
       [3.68860602e-01],
       [3.74738663e-01],
       [8.98062706e-01],
       [9.06712413e-01],
       [8.21819723e-01],
       [8.04088354e-01],
       [2.62775812e-02],
       [5.62069602e-02],
       [8.30556870e-01],
       [1.77518073e-02],
       [9.28580523e-01],
       [2.16764901e-02],
       [1.10921143e-02],
       [8.54937613e-01],
       [9.40868573e-04],
       [3.32959439e-03],
       [8.10911655e-01],
       [7.92732835e-02],
       [1.27947658e-01],
       [9.28932071e-01],
       [9.21355128e-01],
       [1.02924081e-02],
       [5.41776538e-01],
       [8.24389577e-01],
       [8.89250398e-01],
       [6.59367070e-02],
